fix(#269): matching Unit variant payloads (#266)
pattern matching a unit type in a match expression e.g.
```ante
match result
| Ok () -> println "ok"
| Error error -> println error
```
resulted in the following panic when compiling:
```
thread '<unnamed>' panicked at src/mir/validation.rs:
  Switch value type is not an integer, got `Unit`
```
digging in, I think this is because MIR generates effectively a nested
match statement for the `Ok ()` pattern matching. The "discriminant" of
this nested switch is of type Unit, but it creates a switch with cases
of integer, something like:
```
switch Unit
| 0 -> ...
`
which causes the panic.

The fix should be to simply represent Unit in these cases as `0`
so instead we get something like
```
switch 0
| 0 -> ...
```
Again this would probably be resolved in the longer term fix in #238
to filter out zero sized types.