cleanup error handling and add an `init` command (#257)
* cleanup error handling and add an `init` command

Cleans up error handling to surface all errors to the runtime. We use
system exit (1) so we can get a pretty message, we introduce thiserror
so we can pass errors up the chain rather than scattering system exits
everywhere.

Introduces a basic init command which inits a project at the given path
(defaults to `.`). This creates an `ante.toml` and `src/main.an` with a
hello world example. It tries to error out early where applicable.
Example

```
~/Documents/personal/ante on  master ✗ ⌚ 15:21:49
$ ./target/debug/ante init ../hello-world

~/Documents/personal/ante on  master ✗ ⌚ 15:22:05
$ bat ../hello-world/ante.toml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ../hello-world/ante.toml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name = "hello-world"
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~/Documents/personal/ante on  master ✗ ⌚ 15:22:19
$ bat ../hello-world/src/main.an
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ../hello-world/src/main.an
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ main () = println "Hello, World!"
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~/Documents/personal/ante on  master ✗ ⌚ 15:22:39
$ cd ../hello-world

~/Documents/personal/hello-world ⌚ 15:23:06
$ ../ante/target/debug/ante run
Hello, World!

~/Documents/personal/hello-world ⌚ 15:23:19
$ cd ../ante

~/Documents/personal/ante on  master ✗ ⌚ 15:23:23
$ ./target/debug/ante init ../hello-world
error: Failed to init project: Manifest File Already Exists

~/Documents/personal/ante on  master ✗ ⌚ 15:23:29
$
```

Also ran `cargo clippy --fix`

* Update src/dependencies.rs

---------

Co-authored-by: jfecher <jfecher11@gmail.com>